/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.controlador.ControladorProyecto;

/**
 *
 * @author DELL
 */
public class Principal extends javax.swing.JFrame {

    public Object menuItemPrueba;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        new ControladorProyecto(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        parametrosUmbralizacion = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelImagen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelImagenMuestra = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuImagen = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemGrises = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItem90 = new javax.swing.JMenuItem();
        menuItem180 = new javax.swing.JMenuItem();
        menuItem270 = new javax.swing.JMenuItem();
        menuItemZoom = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemInverso = new javax.swing.JMenuItem();
        menuItemUmbral = new javax.swing.JMenuItem();
        menuItemUmbralBinario = new javax.swing.JMenuItem();
        menuItemUmbralGris = new javax.swing.JMenuItem();
        menuItemExtension = new javax.swing.JMenuItem();
        menuItemReduccionGrises = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout parametrosUmbralizacionLayout = new javax.swing.GroupLayout(parametrosUmbralizacion);
        parametrosUmbralizacion.setLayout(parametrosUmbralizacionLayout);
        parametrosUmbralizacionLayout.setHorizontalGroup(
            parametrosUmbralizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        parametrosUmbralizacionLayout.setVerticalGroup(
            parametrosUmbralizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 337, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(labelImagen);

        jScrollPane2.setViewportView(labelImagenMuestra);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menuImagen.setText("Imagen");

        menuItemAbrir.setText("Abrir");
        menuImagen.add(menuItemAbrir);

        jMenuBar1.add(menuImagen);

        jMenu4.setText("Filtros");

        menuItemGrises.setText("Escala de Grises");
        jMenu4.add(menuItemGrises);

        jMenu1.setText("Rotar");

        menuItem90.setText("90°");
        jMenu1.add(menuItem90);

        menuItem180.setText("180°");
        jMenu1.add(menuItem180);

        menuItem270.setText("270°");
        jMenu1.add(menuItem270);

        jMenu4.add(jMenu1);

        menuItemZoom.setText("Interpolacion");
        jMenu4.add(menuItemZoom);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Umbralizacion");

        menuItemInverso.setText("Inverso");
        menuItemInverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInversoActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemInverso);

        menuItemUmbral.setText("Umbral");
        menuItemUmbral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUmbralActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemUmbral);

        menuItemUmbralBinario.setText("Umbral Binario");
        jMenu5.add(menuItemUmbralBinario);

        menuItemUmbralGris.setText("Umbral Gris");
        jMenu5.add(menuItemUmbralGris);

        menuItemExtension.setText("Extension");
        jMenu5.add(menuItemExtension);

        menuItemReduccionGrises.setText("Reduccion de Grises");
        jMenu5.add(menuItemReduccionGrises);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(parametrosUmbralizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(parametrosUmbralizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemInversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInversoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemInversoActionPerformed

    private void menuItemUmbralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUmbralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemUmbralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel labelImagen;
    public javax.swing.JLabel labelImagenMuestra;
    public javax.swing.JMenu menuImagen;
    public javax.swing.JMenuItem menuItem180;
    public javax.swing.JMenuItem menuItem270;
    public javax.swing.JMenuItem menuItem90;
    public javax.swing.JMenuItem menuItemAbrir;
    public javax.swing.JMenuItem menuItemExtension;
    public javax.swing.JMenuItem menuItemGrises;
    public javax.swing.JMenuItem menuItemInverso;
    public javax.swing.JMenuItem menuItemReduccionGrises;
    public javax.swing.JMenuItem menuItemUmbral;
    public javax.swing.JMenuItem menuItemUmbralBinario;
    public javax.swing.JMenuItem menuItemUmbralGris;
    public javax.swing.JMenuItem menuItemZoom;
    public javax.swing.JPanel parametrosUmbralizacion;
    // End of variables declaration//GEN-END:variables
}
