/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import vista.controlador.ControladorProyecto;

/**
 *
 * @author DELL
 */
public class Principal extends javax.swing.JFrame {

    public Object menuItemPrueba;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        new ControladorProyecto(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jPanelInformacion = new javax.swing.JPanel();
        labelRuta = new javax.swing.JLabel();
        labelFormato = new javax.swing.JLabel();
        labelfilas = new javax.swing.JLabel();
        labelColumnas = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelFiltro = new javax.swing.JLabel();
        infoNombre = new javax.swing.JLabel();
        infoRuta = new javax.swing.JLabel();
        infoFilas = new javax.swing.JLabel();
        infoFormato = new javax.swing.JLabel();
        infoColumnas = new javax.swing.JLabel();
        infoFiltro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        labelImagen = new javax.swing.JLabel();
        parametrosUmbralizacion = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        labelImagenMuestra = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuImagen = new javax.swing.JMenu();
        menuItemAbrir = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuItemGrises = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItem90 = new javax.swing.JMenuItem();
        menuItem180 = new javax.swing.JMenuItem();
        menuItem270 = new javax.swing.JMenuItem();
        menuItemZoom = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuItemInverso = new javax.swing.JMenuItem();
        menuItemUmbral = new javax.swing.JMenuItem();
        menuItemUmbralBinario = new javax.swing.JMenuItem();
        menuItemUmbralGris = new javax.swing.JMenuItem();
        menuItemExtension = new javax.swing.JMenuItem();
        menuItemReduccionGrises = new javax.swing.JMenuItem();
        jMenuOperaciones = new javax.swing.JMenu();
        menuItemSuma = new javax.swing.JMenuItem();
        menuItemResta = new javax.swing.JMenuItem();
        menuItemNOT = new javax.swing.JMenuItem();
        menuItemOR = new javax.swing.JMenuItem();
        menuItemAND = new javax.swing.JMenuItem();
        menuItemXOR = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuItemMediaAritmetica = new javax.swing.JMenuItem();
        menuItemMediaGeometrica = new javax.swing.JMenuItem();
        menuItemMediaContraArmonica = new javax.swing.JMenuItem();
        menuItemEstadisticoMediana = new javax.swing.JMenuItem();
        menuItemEstadisticoMaximo = new javax.swing.JMenuItem();
        menuItemEstadisticoMinimo = new javax.swing.JMenuItem();
        menuItemEstadisticoPuntoAPunto = new javax.swing.JMenuItem();
        menuItemMediaSeccion = new javax.swing.JMenuItem();
        Convolucion = new javax.swing.JMenu();
        menuItemConvolucion = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuItemEspectro = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuItemIdealLowPassFilter = new javax.swing.JMenuItem();
        menuItemLowPassFilter = new javax.swing.JMenuItem();
        menuItemIdealHighPassFilter = new javax.swing.JMenuItem();
        menuItemIdealHighPassFilterOrden = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        menuItemCMY = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        menuItemIntensidad = new javax.swing.JMenuItem();
        menuItemMatiz = new javax.swing.JMenuItem();
        menuItemSaturacion = new javax.swing.JMenuItem();
        jMenu11 = new javax.swing.JMenu();
        menuItemErocion = new javax.swing.JMenuItem();
        menuItemDilatacion = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        menuItemPruebaDos = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        jMenu2.setText("File");
        jMenuBar2.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        labelRuta.setText("Ruta:");

        labelFormato.setText("Formato:");

        labelfilas.setText("Filas:");

        labelColumnas.setText("Columnas:");

        labelNombre.setText("Nombre:");

        labelFiltro.setText("Filtro:");

        infoNombre.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        infoRuta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        infoFilas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        infoFormato.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        infoColumnas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        infoFiltro.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanelInformacionLayout = new javax.swing.GroupLayout(jPanelInformacion);
        jPanelInformacion.setLayout(jPanelInformacionLayout);
        jPanelInformacionLayout.setHorizontalGroup(
            jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(labelNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(labelFormato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoFormato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(labelRuta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(labelfilas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoFilas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(labelColumnas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoColumnas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInformacionLayout.createSequentialGroup()
                        .addComponent(labelFiltro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(infoFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelInformacionLayout.setVerticalGroup(
            jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInformacionLayout.createSequentialGroup()
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(infoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRuta)
                    .addComponent(infoRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFormato)
                    .addComponent(infoFormato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelfilas)
                    .addComponent(infoFilas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelColumnas)
                    .addComponent(infoColumnas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFiltro)
                    .addComponent(infoFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(labelImagen);

        javax.swing.GroupLayout parametrosUmbralizacionLayout = new javax.swing.GroupLayout(parametrosUmbralizacion);
        parametrosUmbralizacion.setLayout(parametrosUmbralizacionLayout);
        parametrosUmbralizacionLayout.setHorizontalGroup(
            parametrosUmbralizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        parametrosUmbralizacionLayout.setVerticalGroup(
            parametrosUmbralizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(labelImagenMuestra);

        menuImagen.setText("Imagen");

        menuItemAbrir.setText("Abrir");
        menuImagen.add(menuItemAbrir);

        jMenuBar1.add(menuImagen);

        jMenu4.setText("Filtros");

        menuItemGrises.setText("Escala de Grises");
        jMenu4.add(menuItemGrises);

        jMenu1.setText("Rotar");

        menuItem90.setText("90°");
        jMenu1.add(menuItem90);

        menuItem180.setText("180°");
        jMenu1.add(menuItem180);

        menuItem270.setText("270°");
        jMenu1.add(menuItem270);

        jMenu4.add(jMenu1);

        menuItemZoom.setText("Interpolacion");
        jMenu4.add(menuItemZoom);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Umbralizacion");

        menuItemInverso.setText("Inverso");
        menuItemInverso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemInversoActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemInverso);

        menuItemUmbral.setText("Umbral");
        menuItemUmbral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemUmbralActionPerformed(evt);
            }
        });
        jMenu5.add(menuItemUmbral);

        menuItemUmbralBinario.setText("Umbral Binario");
        jMenu5.add(menuItemUmbralBinario);

        menuItemUmbralGris.setText("Umbral Gris");
        jMenu5.add(menuItemUmbralGris);

        menuItemExtension.setText("Extension");
        jMenu5.add(menuItemExtension);

        menuItemReduccionGrises.setText("Reduccion de Grises");
        jMenu5.add(menuItemReduccionGrises);

        jMenuBar1.add(jMenu5);

        jMenuOperaciones.setText("Operaciones");

        menuItemSuma.setText("Suma");
        menuItemSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSumaActionPerformed(evt);
            }
        });
        jMenuOperaciones.add(menuItemSuma);

        menuItemResta.setText("Resta");
        jMenuOperaciones.add(menuItemResta);

        menuItemNOT.setText("NOT");
        jMenuOperaciones.add(menuItemNOT);

        menuItemOR.setText("OR");
        jMenuOperaciones.add(menuItemOR);

        menuItemAND.setText("AND");
        jMenuOperaciones.add(menuItemAND);

        menuItemXOR.setText("XOR");
        jMenuOperaciones.add(menuItemXOR);

        jMenuBar1.add(jMenuOperaciones);

        jMenu6.setText("Media");

        menuItemMediaAritmetica.setText("Media Aritmetica");
        menuItemMediaAritmetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemMediaAritmeticaActionPerformed(evt);
            }
        });
        jMenu6.add(menuItemMediaAritmetica);

        menuItemMediaGeometrica.setText("Media Geometrica");
        jMenu6.add(menuItemMediaGeometrica);

        menuItemMediaContraArmonica.setText("Media Contra Armonica");
        jMenu6.add(menuItemMediaContraArmonica);

        menuItemEstadisticoMediana.setText("Estadistico Mediana");
        jMenu6.add(menuItemEstadisticoMediana);

        menuItemEstadisticoMaximo.setText("Estadistico Maximo");
        jMenu6.add(menuItemEstadisticoMaximo);

        menuItemEstadisticoMinimo.setText("Estadistico Minimo");
        jMenu6.add(menuItemEstadisticoMinimo);

        menuItemEstadisticoPuntoAPunto.setText("Estadistico Punto A Punto");
        jMenu6.add(menuItemEstadisticoPuntoAPunto);

        menuItemMediaSeccion.setText("Media Seccion");
        jMenu6.add(menuItemMediaSeccion);

        jMenuBar1.add(jMenu6);

        Convolucion.setText("Convolucion");

        menuItemConvolucion.setText("Convolucion");
        Convolucion.add(menuItemConvolucion);

        jMenuBar1.add(Convolucion);

        jMenu7.setText("Espectro");

        menuItemEspectro.setText("Espectro");
        jMenu7.add(menuItemEspectro);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Frecuencias");

        menuItemIdealLowPassFilter.setText("Ideal Low Pass Filter");
        menuItemIdealLowPassFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemIdealLowPassFilterActionPerformed(evt);
            }
        });
        jMenu8.add(menuItemIdealLowPassFilter);

        menuItemLowPassFilter.setText("Low Pass Filter");
        menuItemLowPassFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLowPassFilterActionPerformed(evt);
            }
        });
        jMenu8.add(menuItemLowPassFilter);

        menuItemIdealHighPassFilter.setText("Ideal High Pass Filter");
        jMenu8.add(menuItemIdealHighPassFilter);

        menuItemIdealHighPassFilterOrden.setText("Ideal High Pass Filter Orden");
        jMenu8.add(menuItemIdealHighPassFilterOrden);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("RGB - CMY");

        menuItemCMY.setText("Convertir en CMY");
        menuItemCMY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCMYActionPerformed(evt);
            }
        });
        jMenu9.add(menuItemCMY);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("HSI");

        menuItemIntensidad.setText("Intensidad");
        jMenu10.add(menuItemIntensidad);

        menuItemMatiz.setText("Matiz");
        jMenu10.add(menuItemMatiz);

        menuItemSaturacion.setText("Saturacion");
        jMenu10.add(menuItemSaturacion);

        jMenuBar1.add(jMenu10);

        jMenu11.setText("Morfologicas");

        menuItemErocion.setText("Erocion");
        menuItemErocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemErocionActionPerformed(evt);
            }
        });
        jMenu11.add(menuItemErocion);

        menuItemDilatacion.setText("Dilatacion");
        menuItemDilatacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemDilatacionActionPerformed(evt);
            }
        });
        jMenu11.add(menuItemDilatacion);

        jMenuBar1.add(jMenu11);

        jMenu12.setText("Prueba");

        menuItemPruebaDos.setText("Prueba");
        jMenu12.add(menuItemPruebaDos);

        jMenuBar1.add(jMenu12);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parametrosUmbralizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(parametrosUmbralizacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemInversoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemInversoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemInversoActionPerformed

    private void menuItemUmbralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemUmbralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemUmbralActionPerformed

    private void menuItemSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemSumaActionPerformed

    private void menuItemMediaAritmeticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemMediaAritmeticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemMediaAritmeticaActionPerformed

    private void menuItemIdealLowPassFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemIdealLowPassFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemIdealLowPassFilterActionPerformed

    private void menuItemLowPassFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLowPassFilterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemLowPassFilterActionPerformed

    private void menuItemCMYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCMYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemCMYActionPerformed

    private void menuItemDilatacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemDilatacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemDilatacionActionPerformed

    private void menuItemErocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemErocionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemErocionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu Convolucion;
    public javax.swing.JLabel infoColumnas;
    public javax.swing.JLabel infoFilas;
    public javax.swing.JLabel infoFiltro;
    public javax.swing.JLabel infoFormato;
    public javax.swing.JLabel infoNombre;
    public javax.swing.JLabel infoRuta;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    public javax.swing.JMenu jMenuOperaciones;
    public javax.swing.JPanel jPanelInformacion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelColumnas;
    private javax.swing.JLabel labelFiltro;
    private javax.swing.JLabel labelFormato;
    public javax.swing.JLabel labelImagen;
    public javax.swing.JLabel labelImagenMuestra;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelRuta;
    private javax.swing.JLabel labelfilas;
    public javax.swing.JMenu menuImagen;
    public javax.swing.JMenuItem menuItem180;
    public javax.swing.JMenuItem menuItem270;
    public javax.swing.JMenuItem menuItem90;
    public javax.swing.JMenuItem menuItemAND;
    public javax.swing.JMenuItem menuItemAbrir;
    public javax.swing.JMenuItem menuItemCMY;
    public javax.swing.JMenuItem menuItemConvolucion;
    public javax.swing.JMenuItem menuItemDilatacion;
    public javax.swing.JMenuItem menuItemErocion;
    public javax.swing.JMenuItem menuItemEspectro;
    public javax.swing.JMenuItem menuItemEstadisticoMaximo;
    public javax.swing.JMenuItem menuItemEstadisticoMediana;
    public javax.swing.JMenuItem menuItemEstadisticoMinimo;
    public javax.swing.JMenuItem menuItemEstadisticoPuntoAPunto;
    public javax.swing.JMenuItem menuItemExtension;
    public javax.swing.JMenuItem menuItemGrises;
    public javax.swing.JMenuItem menuItemIdealHighPassFilter;
    public javax.swing.JMenuItem menuItemIdealHighPassFilterOrden;
    public javax.swing.JMenuItem menuItemIdealLowPassFilter;
    public javax.swing.JMenuItem menuItemIntensidad;
    public javax.swing.JMenuItem menuItemInverso;
    public javax.swing.JMenuItem menuItemLowPassFilter;
    public javax.swing.JMenuItem menuItemMatiz;
    public javax.swing.JMenuItem menuItemMediaAritmetica;
    public javax.swing.JMenuItem menuItemMediaContraArmonica;
    public javax.swing.JMenuItem menuItemMediaGeometrica;
    public javax.swing.JMenuItem menuItemMediaSeccion;
    public javax.swing.JMenuItem menuItemNOT;
    public javax.swing.JMenuItem menuItemOR;
    public javax.swing.JMenuItem menuItemPruebaDos;
    public javax.swing.JMenuItem menuItemReduccionGrises;
    public javax.swing.JMenuItem menuItemResta;
    public javax.swing.JMenuItem menuItemSaturacion;
    public javax.swing.JMenuItem menuItemSuma;
    public javax.swing.JMenuItem menuItemUmbral;
    public javax.swing.JMenuItem menuItemUmbralBinario;
    public javax.swing.JMenuItem menuItemUmbralGris;
    public javax.swing.JMenuItem menuItemXOR;
    public javax.swing.JMenuItem menuItemZoom;
    public javax.swing.JPanel parametrosUmbralizacion;
    // End of variables declaration//GEN-END:variables
}
